
  [[redirects]]
  from = "/gtag/js"
  to = "https://www.googletagmanager.com/gtag/js"
  status = 200
  force = true

[[redirects]]
  from = "/gtm.js"
  to = "https://www.googletagmanager.com/gtm.js"
  status = 200
  force = true

[[redirects]]
  from = "/analytics.js"
  to = "https://www.google-analytics.com/analytics.js"
  status = 200
  force = true

[[redirects]]
  from = "/collect"
  to = "https://www.google-analytics.com/collect"
  status = 200
  force = true

[[redirects]]
  from = "/hotjar/*"
  to = "https://static.hotjar.com/:splat"
  status = 200
  force = true


[[headers]]
  for = "/analytics.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/collect"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/gtag/js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/hotjar/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"
