[[redirects]]
  from = "/__third-party-proxy?url=https://www.googletagmanager.com/gtag/js?id=GTM-KKM6ZM7"
  to = "https://www.googletagmanager.com/gtag/js?id=GTM-KKM6ZM7:splat"
  status = 200
  force = true

[[redirects]]
  from = "/__third-party-proxy?url=https://www.google-analytics.com/analytics.js"
  to = "https://www.google-analytics.com/analytics.js:splat"
  status = 200
  force = true